server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heima?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: abc123456
    virtual-host: /
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: itcast
    password: abc123456
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo

# server:
#   port: 8089
# spring:
#   datasource:
#     url: jdbc:mysql://mysql:3306/heima?useSSL=false
#     username: root
#     password: 123
#     driver-class-name: com.mysql.jdbc.Driver
#   rabbitmq:
#     host: 127.0.0.1
#     port: 5672
#     username: itcast
#     password: 123321
#     virtual-host: /
# logging:
#   level:
#     cn.itcast: debug
#   pattern:
#     dateformat: HH:mm:ss:SSS
# mybatis-plus:
#   configuration:
#     map-underscore-to-camel-case: true
#   type-aliases-package: cn.itcast.hotel.pojo